server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xj_oj?useUnicode=true&characterEncoding=UTF-8&useJDBC49CompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: filwy3344
    type: com.alibaba.druid.pool.DruidDataSource
  # 配置servlet的多部分上传文件限制
  servlet:
    multipart:
      # 设置请求的最大大小，超过此大小的请求将被拒绝
      max-request-size: 100MB
      # 设置单个上传文件的最大大小，超过此大小的文件将被拒绝
      max-file-size: 100MB
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        # 最大阻塞等待时间，负数表示没有限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中最大连接数，负数表示没有限制
        max-active: 20
    database: 0
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  devtools:
    restart:
      #设置不参与热部署的文件或文件夹
      exclude: application.yml,static/**,public/**
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  tencent:
    secretId: ${TENCENT_SECRET_ID}//////////////////////////////////////已修改
    secretKey: HMDxVr471jGesvsfHkMuInJm6OWnxueB
    bucket: ap-chengdu
    bucketName: xj-oj-1329750222
    path: https://xj-oj-1329750222.cos.ap-chengdu.myqcloud.com
    qianzui: img
    qianzui-file: file

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
  file:
    name: ./log/onlineoj.log
  logback:
    rollingpolicy: # 持久化
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
      max-file-size: 1MB

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
config:
  jwt:
    # 加密密钥
    secret: weiyuexin_XJ
    # token有效时长
    expire: 604800
    # header 名称
    header: wyx
knife4j:
  enable: true
  basic:
    username: root
    password: root
    enable: true
  openapi:
    title: 在线代码测评系统官方文档
    description: "在线代码测评系统 API 文档"
    email: 2948429338@qq.com
    concat: ChenJiabin
    url: https://127.0.0.1:8080/doc.html
    version: v4.0.2
    license: Apache 2.0
    group:
      controller:
        group-name: 接口
        api-rule: package
        api-rule-resources:
          - top.weiyuexin.controller
